name: releaser
on:
  push:
    tags:
      - 'v*'

jobs:
  release-init-kyverno:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: kyverno/kyverno/.github/workflows/reuse.yaml@main
    with:
      publish_command: docker-publish-initContainer
      digest_command: docker-get-initContainer-digest
      image_name: kyvernopre
      tag: release
      main: cmd/initContainer
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  release-kyverno:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: kyverno/kyverno/.github/workflows/reuse.yaml@main
    with:
      publish_command: docker-publish-kyverno
      digest_command: docker-get-kyverno-digest
      image_name: kyverno
      tag: release
      main: cmd/kyverno
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  release-kyverno-cli:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: kyverno/kyverno/.github/workflows/reuse.yaml@main
    with:
      publish_command: docker-publish-cli
      digest_command: docker-get-cli-digest
      image_name: kyverno-cli
      tag: release
      main: cmd/cli/kubectl-kyverno
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}
  
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.2.1'

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: creekorful/goreportcard-action@v1.0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Set version
        run: |
          echo "KYVERNO_VERSION=$(git describe --match "v[0-9]*")"

      - name :  docker images publish
        run: |
          make docker-publish-sigs
          make push-initContainer

  release-kyverno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.2.1'

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: creekorful/goreportcard-action@v1.0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Set version
        run: |
          echo "KYVERNO_VERSION=$(git describe --match "v[0-9]*")"

      - name: Generate SBOM JSON
        uses: CycloneDX/gh-gomod-generate-sbom@v1
        with:
          version: v1
          args: mod -licenses -json -output kyverno-v${{ env.KYVERNO_VERSION }}-bom.cdx.json

      - uses: actions/upload-artifact@v2
        with:
          name: kyverno-bom-cdx
          path: kyverno-v*-bom.cdx.json

      - name :  docker images publish
        run: |
          make docker-publish-sbom
          make push-kyverno

  release-kyverno-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.2.1'

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: creekorful/goreportcard-action@v1.0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Set version
        run: |
          echo "KYVERNO_VERSION=$(git describe --match "v[0-9]*")"

      - name :  docker images publish
        run: |
          make push-cli
